sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rigel7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rigel7/docker-react npm run test
